### ISSUE TITLE
Ask for advice of f-conjugate

### ISSUE THREAD

**Issue by xiaoyuanzh** [fGAIL3456/fGAIL#3]
Dear author, 
      I notice that you use an nn to estimate f-conjugate. In my opinion, for RKL, KL, JS divergence, the form of f-conjugate is given. And why you use a nn instead?

looking for your reply.
Best, Xiaoyuan

**Comment by fGAIL3456** [comment]
Hi Xiaoyuan,

Thank you for your comment. This repository is for the paper "f-GAIL: Learning f-Divergence for Generative Adversarial Imitation Learning" (https://arxiv.org/abs/2010.01207), which aims at finding a good f-divergence for the GAIL model. Therefore, we are modeling the f-divergence instead of using a predefined f-divergence.

Many Thanks,
Xin Zhang

**Comment by fGAIL3456** [comment]
Hi Xiaoyuan,

Thank you for your comment. This repository is for the paper "f-GAIL: Learning f-Divergence for Generative Adversarial Imitation Learning" (https://arxiv.org/abs/2010.01207), which aims at finding a good f-divergence for the GAIL model. Therefore, we are modeling the f-divergence instead of using a predefined f-divergence.

Many Thanks,
Xin Zhang
